name: photos_native
description: High performance Flutter plugin for photos library. It can load photo albums, load image/thumnail, save, share...
version: 0.0.5
homepage: https://annotium.github.io

environment:
  sdk: '^3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  crypto: ^3.0.3
  equatable: ^2.0.5
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: dev.annotium.photos_native
        pluginClass: PhotosNativePlugin
      ios:
        pluginClass: PhotosNativePlugin
